import './globals.css';
import Header from './Header';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>NextJS13 Lab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="bg-slate-800 text-slate-100 h-screen flex flex-col overflow-hidden">
        <Header />
        <main className="flex flex-col flex-1 bg-gray-700">{children}</main>
      </body>
    </html>
  );
}
